### ISSUE TITLE
Recently added

### ISSUE THREAD

**Issue by mike-ferenduros** [mike-ferenduros/ChunkyTNG-issues#2]
Add a listing view that lists recently synced comics, grouped into sections according to the sync-date (so everything that got added in one sync is grouped together).

Could be either a separate listing per root folder, or a single unified listing with the app's entire sync history.

Figure out where to put it:
* Put a folder-like item at the start of in each root folder
* Link from the context-menu of each root folder
* Link somewhere from the root view
* Horizontal scroll in the root view, similar to the recently-read (maybe you toggle between the two)

Should be searchable, with search-results grouped 

Issues:
* Sync history depends on when you pressed the sync buttons and in what order, so it will look different on different devices. In the absence of reliable server timestamps, this seems unavoidable
* If a comic appears in multiple folders (eg. Ubooquity can have the same comic in 'folders', 'all' and 'recents'), do we want to see only the comic's first appearance, or a separate entry for each?
* For OPDS servers that have 'recently added' smart folders, this collides with that; you'll end up with a 'Recently added to "Recently Added"' view

**Comment by AnthonyFaxlandez** [comment]
> Figure out where to put it:
> 
> - Put a folder-like item at the start of in each root folder
> - Link from the context-menu of each root folder
> - Link somewhere from the root view
> - Horizontal scroll in the root view, similar to the recently-read (maybe you toggle between the two)

Honestly while the clean minimalist look is great, have you thought about adding a UITabBarController and having a "For You" tab? It definitely seems to be the trend lately with apps that do any kind of smart grouping of objects. It would let you keep the current view focused on your library of synced folders while moving things like Recently Added (and Currently Reading or whatever else you may want to do) in to its own view. 

> If a comic appears in multiple folders (eg. Ubooquity can have the same comic in 'folders', 'all' and 'recents'), do we want to see only the comic's first appearance, or a separate entry for each?

That depends on if you go with a separate listing per root folder, or a single unified listing. If it's per root folder then you would want a separate entry for each. If you do a single unified listing then it's probably better to filter out duplicates. 

What you could do too is make a single unified listing and allow the user to include/exclude certain folders(maybe a toggle in the folder listing - "Include in Recents"). For example I personally would care about the newest added comics in my "Current" and "Indie" folders but I don't really care about the newest comics added to my "Library" folder. If I could have the latest comics from "Current" and "Indie" in a single, unified listing that filters out duplicates that would be awesome.

**Comment by mike-ferenduros** [comment]
A tab-controller is not a bad idea... I tried but abandoned various kinds of multiple root views a while ago, but only because it was hard to make them cooperate with drag'n'drop. Since I removed d&d I should probably revisit the idea.

**Comment by mike-ferenduros** [comment]
Test implementation currently accessible from root-folder context menu, as 'sync history'

When you have a lot of small syncs (eg weekly updates), it's useful, but until you've built up that sync history, it's kinda useless. And for users who aren't syncing regular, small updates, it's not that useful anyway.
Hence it should probably be a little hidden away in the UI.
